--- !ruby/object:VR_ENV
browser: google-chrome
width: 1278
height: 968
panel_pos: 540
backup_path: /home/eric
tab_spaces: 2
run_command_line: ruby simple_ruby_gui
open_files:
- /home/mat/Documents/Ruby/cmarking2/simple_ruby_gui
open_folders:
- /home/mat/Documents/Ruby/cmarking2
- /home/mat/Documents/Ruby/cmarking2/bin
current_file: /home/mat/Documents/Ruby/cmarking2/simple_ruby_gui
glade_path: glade-gtk2
font_name: Monospace 10
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
glade_box: !ruby/object:VR::SimpleComboBoxEntry {}
browser_box: !ruby/object:VR::SimpleComboBoxEntry {}
