--- !ruby/object:VR_ENV
browser: google-chrome
width: 1280
height: 995
panel_pos: 540
backup_path: /home/eric
tab_spaces: 2
run_command_line: ruby vr_gui
open_files:
- /home/mat/Documents/Ruby/cmarking2/vr_gui
- /home/mat/Documents/Ruby/cmarking2/bin/ReportMarkerGUI.rb
open_folders:
- /home/mat/Documents/Ruby/cmarking2
- /home/mat/Documents/Ruby/cmarking2/bin
- /home/mat/Documents/Ruby/cmarking2/bin/glade
current_file: /home/mat/Documents/Ruby/cmarking2/bin/ReportMarkerGUI.rb
glade_path: glade-gtk2
font_name: Monospace 10
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
glade_box: !ruby/object:VR::SimpleComboBoxEntry {}
browser_box: !ruby/object:VR::SimpleComboBoxEntry {}
